export const Screen_Routes = {
  Intro: 'Intro',
  Login: 'Login',
  AuthNavigator: 'AuthNavigator',
  MainNavigator:'MainNavigot',
  Home:'Home',
  HomeNavigator:'HomeNavigator',
  PromoDetails:'PromoDetails',
  CarDetails : 'CarDetails',
  AllReviews:'AllReviews',
  Checkout:'Checkout',
  ProtectionPlans:'ProtectionPlans',
  FinalCheckout:'FinalCheckout',
  Trip:'Trip',
  Profile:'Profile',
  Add:'Add',
  Chat:'Chat',
  AddCarScreen2:'AddCarScreen2',
  AddCarScreen3:'AddCarScreen3',
  AddCarScreen4:'AddCarScreen4',
  FinalAddCar:'FinalAddCar',
  MoreCars:'MoreCars',
  Review:'Review',
};
